#!/usr/bin/env python

import sys, re
from subprocess import check_output

branch = check_output(['git', 'symbolic-ref', '--short', 'HEAD']).strip()

if branch == 'main':
    print ('Access denied! You can not push directly to main, create a pull request and merge into main!')
    sys.exit(1)