#!/usr/bin/env python

import sys, re
from subprocess import check_output

commit_msg_filepath = sys.argv[1]

branch = check_output(['git', 'symbolic-ref', '--short', 'HEAD']).strip()

error_message = "commit-msg: ERROR! The commit message must start with '%s'"
required_message = "Issue-[0-9:]"

with open(commit_msg_filepath, 'r') as f:
    content = f.read()
    if not re.match(r"^(Issue)-[0-9:]+", content):
        print (error_message % required_message)
        sys.exit(1)